---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-world-on-gke-public"
  namespace: "default"
  labels:
    app: "hello-world-on-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "hello-world-on-gke"
  type: "LoadBalancer"
  loadBalancerIP: ""